# Generated by Django 2.2.1 on 2019-05-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='John Doe', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.Driver'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=6)),
                ('vehicle_class', models.CharField(max_length=40)),
                ('capacity', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.Driver')),
            ],
        ),
    ]
