# Generated by Django 2.2.1 on 2019-05-16 17:35

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190513_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
