# Generated by Django 2.2.1 on 2019-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_job_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('fragility', models.IntegerField()),
                ('Weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
