# Generated by Django 2.2.1 on 2019-05-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20190517_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='Weight',
            new_name='weight',
        ),
    ]
